### PR TITLE
drop INI file projects

### PR DESCRIPTION
**Pull request by leo-schick**
Hi @torstenklement ,

I suggest to remove the INI file projects libfintx.Settings and libfintx.Sample.INIFile which seem not to be used anywhere in the libfintx library.

If someone needs a INI parser, I would recommend other nuget packages like [ini-parser](https://www.nuget.org/packages/ini-parser/#readme-body-tab). I think the removal of this would make the library simpler and easier to understand.

### CODE REVIEW

**Comment by torstenklement** [comment]
@leo-schick not able to merge. Can you please review.

**Comment by leo-schick** [comment]
@torstenklement please try once more.

**Comment by leo-schick** [comment]
@torstenklement FYI if you wanted to delete the unlisted libfintx package, this is not possible. See [How to remove NuGet Package from server?](https://stackoverflow.com/questions/11654652/how-to-remove-nuget-package-from-server)

**Comment by torstenklement** [comment]
Ini project is already in use by customers. That's the reason I need to reject here.

**Pull request closed without merging**
